### ISSUE TITLE
Regularly pull zenodo data via GitHub actions

### ISSUE THREAD

**Issue by korenmiklos** [REStud/report#15]
Download and view stats on zenodo are not version or timestamped. Set up a GH action to pull this data monthly so that we can track how the visibility of each Zenodo package has changed over time.

**Comment by korenmiklos** [comment]
https://github.com/kiss-oliver/nevjegyzek/blob/gh-pages/.github/workflows/main.yml

**Comment by korenmiklos** [comment]
For example, this works:
```
name: Model Evaluation Workflow
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  eval_python:
    name: Model Evaluations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - run: pip install --upgrade pip
      - run: pip install setuptools
      - run: pip install pandas
      - run: pip install gitpython
      - name: Create report file
        run: cd Evaluation/; python3 evaluate.py
      - name: Commit report
        run: |
          git config --global user.name 'Automated Model Evaluator'
          git config --global user.email 'gnn_chapter@noreply.github.com'
          git add Evaluations/*
          git commit -m "feat: add automated model evaluations"
          git push
```
